### PR TITLE
Starting a pull request to demonstrate

### PR DESCRIPTION
**Pull request by DavidLiedle**
I changed one tiny thing to show the workflow here:

- Branch is created in ezsystems/specs
- We create our own branches, and submit pull requests to the "main" branch there
- We discuss here, in the pull request (before merging)
 
Note: This PR is messy, I know. The next one will be cleaner. I was experimenting and writing down steps, and it got messy. :)

https://github.com/ezsystems/specs/issues/4

### CODE REVIEW

**Comment by DavidLiedle** [comment]
Added a USE_CASE document

**Review by supriyabhargava — APPROVED** [review]

**Review by rolandbenedetti — APPROVED** [review]
I still think providing comment only on PR or commits is somehow a strong constraint, but may be I'm wrong and we can change the way we think about commenting. I approve for now, but let's keep in mind we are experimenting it. What matter the most is efficiency of specifying and ease for users to review and access to specs.

**Review by inakijv — APPROVED** [review]
definitely maybe ;-)

**Comment by DavidLiedle** [comment]
Good feedback. Thanks everyone! 3 approvals on this, so I will merge. :shipit:

**Pull request merged**
