### PR TITLE
- Added requirements for initial Docker prototype round.

### PR DESCRIPTION
**Pull request by papelipe**
I created the initial requirements on a high level for the init of a new project environment on Docker and creating a new developer instance.

### CODE REVIEW

**Comment by andrerom** [comment]
@DavidLiedle the use of `"As an eZ Engineer, want.."` should rather be `"As a Developer, I want .."` here right? As the user is rather the Partner/Community developer.

**Comment by andrerom** [comment]
@DavidLiedle any input on above to be able to move forward?

Imho this should replace https://github.com/ezsystems/requirements/pull/5 which is not requirements at all (but this is).

**Comment by andrerom** [comment]
Returning to this, some things that might be missing in the requirements or should be clarified:
- Are there any requirements on deployment? As in target platforms?
- And are there any requirement for the other needs during development pipeline, like covering needs for UAT?
- Should this cover needs for easily taking the project between the different stages of the flow, like for instance being able to swap UAT branch into prod?

**Comment by DavidLiedle** [comment]
@andrerom Yes, this entire repo is 'officially closed', pending the resolution of the trailing conversations and decisions that were/are under discussion to be migrated over to ezsystems/requirements

**Comment by andrerom** [comment]
the questions and review input still stands.

**Comment by DavidLiedle** [comment]
> ...pending the resolution of the trailing conversations and decisions that were/are under discussion...

Yes, we should resolve here, then I'll open a PR that submits the results of this conversation over to the new repo.

**Comment by DavidLiedle** [comment]
Quick-link view of files: https://github.com/ezsystems/specs/pull/28/commits/ec1a1b38b4fd94a02b51932b29fcbf6632279b7f

**Comment by andrerom** [comment]
Moved to https://github.com/ezsystems/requirements/pull/24

**Pull request closed without merging**
